// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardList: typeof import('./src/components/CardList/CardList.vue')['default']
    CardListItem: typeof import('./src/components/CardList/CardListItem.vue')['default']
    DepartmentSelect: typeof import('./src/components/Selects/DepartmentSelect.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    List: typeof import('./src/components/List/index.vue')['default']
    MaterialSelect: typeof import('./src/components/Selects/MaterialSelect.vue')['default']
    OpenWindow: typeof import('./src/components/OpenWindow/index.vue')['default']
    PrintOrder: typeof import('./src/components/PrintPage/PrintOrder.vue')['default']
    PrintTurn: typeof import('./src/components/PrintPage/PrintTurn.vue')['default']
    ProcedureSelect: typeof import('./src/components/Selects/ProcedureSelect.vue')['default']
    ProDescriptions: typeof import('element-pro-components')['ProDescriptions']
    ProForm: typeof import('element-pro-components')['ProForm']
    ProSelect: typeof import('element-pro-components')['ProSelect']
    ProTable: typeof import('element-pro-components')['ProTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTips: typeof import('./src/components/ScrollTips.vue')['default']
    StandardRemarkSelect: typeof import('./src/components/Selects/StandardRemarkSelect.vue')['default']
    SvnIcon: typeof import('./src/components/SvnIcon/index.vue')['default']
    TableSearch: typeof import('./src/components/TableSearch/index.vue')['default']
    UserSelect: typeof import('./src/components/Selects/UserSelect.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
